config/routes.rb
Rails.application.routes.draw do
  resources :profesores
  devise_for :users
  scope '/administrador' do
    resources :users
  end

  get 'inicio', to: 'homepage#index', as: 'mainpage'
  get 'informacion', to: 'information#index', as: 'info'
  get 'seguimiento', to: 'follow#index', as: 'seg_info'
  get 'registro_horas', to: 'hours#index', as: 'hours_show'
  get 'registro_horas/editar/:id', to: 'hours#edit', as: 'hours_edit'
  get '/administrador/users', to: 'users#index', as: 'user_show'
  
  resources :hours
  resources :users
  resources :roles

  root to: 'profile#index'
end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :user

  def traerEstudiante
    #se debe de llamar en HourController#create
    #consulte a la DB, tabla docenteVSestudiante
    #En un droplist, traer los estudiantes asociados al docente (a traves del @user.id)
    #Cuando le de submit, debe de hacer un Post, referenciando al estudiante que se eligio en el droplist
  end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  #before_action :set_hour, only: %i[ show edit update destroy ]

  # GET /hours or /hours.json
  def index
    @hours = Hour.all
  end

  # GET /hours/1 or /hours/1.json
  def show
  end

  # GET /hours/new
  def new
    #@hour = Hour.new
  end

  # GET /hours/1/edit
  def edit
  end

  # POST /hours or /hours.json
  def create
    #@hour = Hour.new(hour_params)
    @hour.user_id = current_user.id
    
    respond_to do |format|
      if @hour.save
        format.html { redirect_to @hour, notice: "Hour was successfully created." }
        format.json { render :show, status: :created, location: @hour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hours/1 or /hours/1.json
  def update
    respond_to do |format|
      if @hour.update(hour_params)
        format.html { redirect_to @hour, notice: "Hour was successfully updated." }
        format.json { render :show, status: :ok, location: @hour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1 or /hours/1.json
  def destroy
    @hour.destroy
    respond_to do |format|
      format.html { redirect_to hours_url, notice: "Hour was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
=begin    def set_hour
      @hour = Hour.find(params[:id])
    end
=end
    # Only allow a list of trusted parameters through.
    def hour_params
      params.require(:hour).permit(:user_id, :number_hours, :observations)
    end
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/views/hours/_form.html.erb
<%= form_with(model: hour) do |form| %>
  <% if hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hour.errors.count, "error") %> prohibited this hour from being saved:</h2>

      <ul>
        <% hour.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Número_de_Horas %>
    <%= form.number_field :number_hours, class:"inputmid form-group"%>
  </div>

  <div class="field">
    <%= form.label :Observaciones %><br>
    <%= form.text_area :observations, class:"inputobs" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hours/edit.html.erb
<body>
<div class="container-fluid">
    <div class="row">
        <div class="topnav col-md-12 themed-grid-col" style="border-bottom: 2px solid #000"></div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="inicio#page-top">Alpha Services - Inicio</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link"%></li>
                    <li class="nav-item"><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete , class:"nav-link"%></li>
                    <% else%>
                    <li class="nav-item"><%= link_to "Iniciar Sesión", new_user_session_path , class:"nav-link"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
        </nav>

    <div class="col-0">
        <ul class="leftnav" style="border-right: 2px solid #000;">
            <li><%= link_to 'Perfil', root_path, class:'leftunselectfont' %></li>
            <li><%= link_to 'Informacion', info_path, class:'leftunselectfont' %></li>
            <li><%= link_to 'Encargado Seguimiento', seg_info_path, class:'leftunselectfont' %></li>
            <li><%= link_to 'Horas Registradas', hours_show_path, class:'leftselectfont' %></li>
            
            <img class="imgmarg" src="../assets/img/Asesc.png" alt="">
        </ul>
    </div>  
    <div class="container px-4 px-lg-5 col-7">
        <p class="datatit">ACTUALIZACION DEL PROCESO:</p> 
   
        <%= render 'form', hour: @hour %>

        <%= link_to 'Show', @hour %> |
        <%= link_to 'Back', hours_path %>
    </div>
 </div>

app/views/hours/index.html.erb
<body>
<div class="container-fluid">
    <div class="row">
        <div class="topnav col-md-12 themed-grid-col" style="border-bottom: 2px solid #000"></div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="inicio#page-top">Alpha Services - Inicio</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link"%></li>
                    <li class="nav-item"><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete , class:"nav-link"%></li>
                    <% else%>
                    <li class="nav-item"><%= link_to "Iniciar Sesión", new_user_session_path , class:"nav-link"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
        </nav>
      
  <div class="col-0">
    <ul class="leftnav" style="border-right: 2px solid #000;">
      <li><%= link_to 'Perfil', root_path, class:'leftunselectfont' %></li>
      <li><%= link_to 'Informacion', info_path, class:'leftunselectfont' %></li>
      <li><%= link_to 'Encargado Seguimiento', seg_info_path, class:'leftunselectfont' %></li>
      <li><%= link_to 'Horas Registradas', hours_show_path, class:'leftselectfont' %></li>

      <img class="imgmarg" src="../assets/img/Asesc.png" alt="">
    </ul>
  </div>

    <div class="container px-4 px-lg-5 col-7">
      <p class="datatit">Horas Registradas: </p> 
      <table class="tabla">
        <thead>
          <tr>
            <th>Estudiantes Asociados</th>
            <th>Número de Horas Completadas</th>
            <th>Observaciones</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @hours.each do |hour| %>
            <tr>
              <td><%= hour.user.name %></td>
              <td><%= hour.number_hours %></td>
              <td><%= hour.observations %></td>
              <td><%= link_to 'Ver', hour %></td>
              <td><%= link_to 'Editar', edit_hour_path(hour) %></td>
              <td><%= link_to 'Eliminar', hour, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>  
      <%= link_to 'Crear nuevo registro', new_hour_path%>
    </div>
</div> 
<div class="marg text-muted">Copyright &copy; 2021 - Alpha Service</div>
</body>

<br>

app/views/hours/new.html.erb
<body>
<div class="container-fluid">
    <div class="row">
        <div class="topnav col-md-12 themed-grid-col" style="border-bottom: 2px solid #000"></div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="../../inicio#page-top">Alpha Services - Inicio</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link"%></li>
                    <li class="nav-item"><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete , class:"nav-link"%></li>
                    <% else%>
                    <li class="nav-item"><%= link_to "Iniciar Sesión", new_user_session_path , class:"nav-link"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
        </nav>

    <div class="col-0">
        <ul class="leftnav" style="border-right: 2px solid #000;">
            <li><%= link_to 'Perfil', root_path, class:'leftselectfont' %></li>
            <li><%= link_to 'Informacion', info_path, class:'leftunselectfont' %></li>
            <li><%= link_to 'Encargado Seguimiento', seg_info_path, class:'leftunselectfont' %></li>
            <li><%= link_to 'Horas Registradas', hours_show_path, class:'leftunselectfont' %></li>
            
            <img class="imgmarg" src="../assets/img/Asesc.png" alt="">
        </ul>
    </div>  
    <div class="container px-4 px-lg-5 col-7">

        <h1>Nuevo Registro de Horas</h1>

        <%= render 'form', hour: @hour %>

        <%= link_to 'Volver', hours_path %>
    </div>

app/views/hours/show.html.erb
<body>
<div class="container-fluid">
    <div class="row">
        <div class="topnav col-md-12 themed-grid-col" style="border-bottom: 2px solid #000"></div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="inicio#page-top">Alpha Services - Inicio</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link"%></li>
                    <li class="nav-item"><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete , class:"nav-link"%></li>
                    <% else%>
                    <li class="nav-item"><%= link_to "Iniciar Sesión", new_user_session_path , class:"nav-link"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
        </nav>

    <div class="col-0">
        <ul class="leftnav" style="border-right: 2px solid #000;">
            <li><%= link_to 'Perfil', root_path, class:'leftunselectfont' %></li>
            <li><%= link_to 'Informacion', info_path, class:'leftunselectfont' %></li>
            <li><%= link_to 'Encargado Seguimiento', seg_info_path, class:'leftunselectfont' %></li>
            <li><%= link_to 'Horas Registradas', hours_show_path, class:'leftselectfont' %></li>
            
            <img class="imgmarg" src="../assets/img/Asesc.png" alt="">
        </ul>
    </div>  
    <div class="container px-4 px-lg-5 col-7">
    <p class="datatit">Información Sobre Horas Registradas:</p> 

    <ul>
    <li>
    <p>
      <strong>Estudiantes Asociados:</strong>
      <%= @hour.user.name %>
    </p>
    </li>

    <li>
    <p>
      <strong>Number hours:</strong>
      <%= @hour.number_hours %>
    </p>
    </li>

    <li>
    <p>
      <strong>Observations:</strong>
      <%= @hour.observations %>
    </p>
    </li>
    </ul>
  
    <%= link_to 'Editar', edit_hour_path(@hour) %> |
    <%= link_to 'Volver', hours_path %>