config/routes.rb
Rails.application.routes.draw do
  resources :profesores
  devise_for :users
  scope '/administrador' do
    resources :users
  end

  get 'inicio', to: 'homepage#index', as: 'mainpage'
  get 'informacion', to: 'information#index', as: 'info'
  get 'seguimiento', to: 'follow#index', as: 'seg_info'
  get 'registro_horas', to: 'hours#index', as: 'hours_show'
  get 'registro_horas/editar/:id', to: 'hours#edit', as: 'hours_edit'
  get '/administrador/users', to: 'users#index', as: 'user_show'
  
  resources :hours
  resources :users
  resources :roles

  root to: 'profile#index'
end

app/models/profesore.rb
class Profesore < ApplicationRecord
end

app/controllers/profesores_controller.rb
class ProfesoresController < ApplicationController
  before_action :set_profesore, only: %i[ show edit update destroy ]

  # GET /profesores or /profesores.json
  def index
    @profesores = Profesore.all
  end

  # GET /profesores/1 or /profesores/1.json
  def show
  end

  # GET /profesores/new
  def new
    @profesore = Profesore.new
  end

  # GET /profesores/1/edit
  def edit
  end

  # POST /profesores or /profesores.json
  def create
    @profesore = Profesore.new(profesore_params)

    respond_to do |format|
      if @profesore.save
        format.html { redirect_to @profesore, notice: "Profesore was successfully created." }
        format.json { render :show, status: :created, location: @profesore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profesore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesores/1 or /profesores/1.json
  def update
    respond_to do |format|
      if @profesore.update(profesore_params)
        format.html { redirect_to @profesore, notice: "Profesore was successfully updated." }
        format.json { render :show, status: :ok, location: @profesore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profesore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesores/1 or /profesores/1.json
  def destroy
    @profesore.destroy
    respond_to do |format|
      format.html { redirect_to profesores_url, notice: "Profesore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesore
      @profesore = Profesore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profesore_params
      params.require(:profesore).permit(:deparamento, :salon, :nombre)
    end
end

app/helpers/profesores_helper.rb
module ProfesoresHelper
end

app/views/profesores/_form.html.erb
<%= form_with(model: profesore) do |form| %>
  <% if profesore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profesore.errors.count, "error") %> prohibited this profesore from being saved:</h2>

      <ul>
        <% profesore.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :deparamento %>
    <%= form.text_field :deparamento %>
  </div>

  <div class="field">
    <%= form.label :salon %>
    <%= form.number_field :salon %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profesores/edit.html.erb
<h1>Editing Profesore</h1>

<%= render 'form', profesore: @profesore %>

<%= link_to 'Show', @profesore %> |
<%= link_to 'Back', profesores_path %>

app/views/profesores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profesores</h1>

<table>
  <thead>
    <tr>
      <th>Deparamento</th>
      <th>Salon</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesores.each do |profesore| %>
      <tr>
        <td><%= profesore.deparamento %></td>
        <td><%= profesore.salon %></td>
        <td><%= profesore.nombre %></td>
        <td><%= link_to 'Show', profesore %></td>
        <td><%= link_to 'Edit', edit_profesore_path(profesore) %></td>
        <td><%= link_to 'Destroy', profesore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profesore', new_profesore_path %>

app/views/profesores/new.html.erb
<h1>New Profesore</h1>

<%= render 'form', profesore: @profesore %>

<%= link_to 'Back', profesores_path %>

app/views/profesores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deparamento:</strong>
  <%= @profesore.deparamento %>
</p>

<p>
  <strong>Salon:</strong>
  <%= @profesore.salon %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @profesore.nombre %>
</p>

<%= link_to 'Edit', edit_profesore_path(@profesore) %> |
<%= link_to 'Back', profesores_path %>