config/routes.rb
Rails.application.routes.draw do
  resources :profesores
  devise_for :users
  scope '/administrador' do
    resources :users
  end

  get 'inicio', to: 'homepage#index', as: 'mainpage'
  get 'informacion', to: 'information#index', as: 'info'
  get 'seguimiento', to: 'follow#index', as: 'seg_info'
  get 'registro_horas', to: 'hours#index', as: 'hours_show'
  get 'registro_horas/editar/:id', to: 'hours#edit', as: 'hours_edit'
  get '/administrador/users', to: 'users#index', as: 'user_show'
  
  resources :hours
  resources :users
  resources :roles

  root to: 'profile#index'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role, optional: true
  has_many :items, dependent: :destroy
  validates :name, presence: true
  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: 'Estudiante' if role.nil?
  end

  def administrador?
    role.name == 'Administrador'
  end

  def docente?
    role.name == 'Docente'
  end

  def estudiante?
    role.name == 'Estudiante'
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_user, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    #@user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    #@user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "El usuario ha sido creado con exito!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if user_params[:password].blank?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end
  
    successfully_updated = if needs_password?(@user, user_params)
                             @user.update(user_params)
                           else
                             @user.update_without_password(user_params)
                           end
  
    if successfully_updated
      redirect_to @user, notice: 'El usuario ha sido actualizado con exito!'
    else
      render :edit
    end
  end

  private

  def needs_password?(_user, params)
    params[:password].present?
  end


  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "El usuario ha sido destruido!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
=begin    def set_user
      @user = User.find(params[:id])
    end
=end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :email,
        :password,
        :password_confirmation,
        :name,
        :role_id
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= collection_select(
    :user, :role_id, Role.all, :id, :name, { prompt: true }
  ) %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :identity_document %>
    <%= form.number_field :identity_document %>
  </div>

  <div class="field">
    <%= form.label :type_document %>
    <%= form.text_field :type_document %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :municipality %>
    <%= form.text_field :municipality %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password, placeholder: "Dejame en blanco si no quieres cambiarla" %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<body>
<div class="container-fluid">
    <div class="row">
        <div class="topnav col-md-12 themed-grid-col" style="border-bottom: 2px solid #000"></div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="inicio#page-top">Alpha Services - Inicio</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link"%></li>
                    <li class="nav-item"><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete , class:"nav-link"%></li>
                    <% else%>
                    <li class="nav-item"><%= link_to "Iniciar Sesión", new_user_session_path , class:"nav-link"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
        </nav>
      
  <div class="col-0">
    <ul class="leftnav" style="border-right: 2px solid #000;">
        <% if current_user.administrador?%>
        <li><%= link_to 'Perfil', root_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Administrar Usuarios', user_show_path, class:'leftselectfont' %></li>
        <% else%>
        <li><%= link_to 'Perfil', root_path, class:'leftselectfont' %></li>
        <li><%= link_to 'Informacion', info_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Encargado Seguimiento', seg_info_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Horas Registradas', hours_show_path, class:'leftunselectfont' %></li>
        <%end%>
        <img class="imgmarg" src="../assets/img/Asesc.png" alt="">
    </ul>

</div>

    <div class="container px-4 px-lg-5 col-7">
        <p class="datatit">Editar Usuario: </p> 

        <%= render 'form', user: @user %>

        <%= link_to 'Show', @user %> |
        <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<body>
<div class="container-fluid">
    <div class="row">
        <div class="topnav col-md-12 themed-grid-col" style="border-bottom: 2px solid #000"></div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="../../inicio#page-top">Alpha Services - Inicio</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link"%></li>
                    <li class="nav-item"><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete , class:"nav-link"%></li>
                    <% else%>
                    <li class="nav-item"><%= link_to "Iniciar Sesión", new_user_session_path , class:"nav-link"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
        </nav>
        <p class="datatit">Datos Usuarios: </p> 

<table class="tabla">
  <thead>
    <tr>
      <th>Rol</th>
      <th>Email</th>
      <th colspan="1"></th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Documento Identidad</th>
      <th>Tipo Documento</th>
      <th>Telefono</th>
      <th>Municipio</th>
      <th>Dirección</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.role.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.identity_document %></td>
        <td><%= user.type_document %></td>
        <td><%= user.phone %></td>
        <td><%= user.municipality %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Nuevo Usuario', new_user_path , class: 'btn btn-primary'%>

app/views/users/new.html.erb
<body>
<div class="container-fluid">
    <div class="row">
        <div class="topnav col-md-12 themed-grid-col" style="border-bottom: 2px solid #000"></div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="inicio#page-top">Alpha Services - Inicio</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link"%></li>
                    <li class="nav-item"><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete , class:"nav-link"%></li>
                    <% else%>
                    <li class="nav-item"><%= link_to "Iniciar Sesión", new_user_session_path , class:"nav-link"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
        </nav>
      
  <div class="col-0">
    <ul class="leftnav" style="border-right: 2px solid #000;">
        <% if current_user.administrador?%>
        <li><%= link_to 'Perfil', root_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Administrar Usuarios', user_show_path, class:'leftselectfont' %></li>
        <% else%>
        <li><%= link_to 'Perfil', root_path, class:'leftselectfont' %></li>
        <li><%= link_to 'Informacion', info_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Encargado Seguimiento', seg_info_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Horas Registradas', hours_show_path, class:'leftunselectfont' %></li>
        <%end%>
        <img class="imgmarg" src="../assets/img/Asesc.png" alt="">
    </ul>

</div>

    <div class="container px-4 px-lg-5 col-7">
    
    <p class="datatit">Nuevo Usuario: </p> 

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

</div>

app/views/users/show.html.erb
<body>
<div class="container-fluid">
    <div class="row">
        <div class="topnav col-md-12 themed-grid-col" style="border-bottom: 2px solid #000"></div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="inicio#page-top">Alpha Services - Inicio</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <% if user_signed_in? %>
                    <li class="nav-item"><%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link"%></li>
                    <li class="nav-item"><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete , class:"nav-link"%></li>
                    <% else%>
                    <li class="nav-item"><%= link_to "Iniciar Sesión", new_user_session_path , class:"nav-link"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
        </nav>
      
  <div class="col-0">
    <ul class="leftnav" style="border-right: 2px solid #000;">
        <% if current_user.administrador?%>
        <li><%= link_to 'Perfil', root_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Administrar Usuarios', user_show_path, class:'leftselectfont' %></li>
        <% else%>
        <li><%= link_to 'Perfil', root_path, class:'leftselectfont' %></li>
        <li><%= link_to 'Informacion', info_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Encargado Seguimiento', seg_info_path, class:'leftunselectfont' %></li>
        <li><%= link_to 'Horas Registradas', hours_show_path, class:'leftunselectfont' %></li>
        <%end%>
        <img class="imgmarg" src="../assets/img/Asesc.png" alt="">
    </ul>

</div>

    <div class="container px-4 px-lg-5 col-7">
      <p class="datatit">Informacion Usuario: </p> 
      <p>
        <strong>Role:</strong>
        <%= @user.role.name %>
      </p>

      <p>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>

      <p>
        <strong>Last name:</strong>
        <%= @user.last_name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>

      <p>
        <strong>Identity document:</strong>
        <%= @user.identity_document %>
      </p>

      <p>
        <strong>Type document:</strong>
        <%= @user.type_document %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= @user.phone %>
      </p>

      <p>
        <strong>Municipality:</strong>
        <%= @user.municipality %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @user.address %>
      </p>

      <%= link_to 'Edit', edit_user_path(@user) %> |
      <%= link_to 'Back', users_path %>
  </div>