config/routes.rb
Rails.application.routes.draw do
  resources :profesores
  devise_for :users
  scope '/administrador' do
    resources :users
  end

  get 'inicio', to: 'homepage#index', as: 'mainpage'
  get 'informacion', to: 'information#index', as: 'info'
  get 'seguimiento', to: 'follow#index', as: 'seg_info'
  get 'registro_horas', to: 'hours#index', as: 'hours_show'
  get 'registro_horas/editar/:id', to: 'hours#edit', as: 'hours_edit'
  get '/administrador/users', to: 'users#index', as: 'user_show'
  
  resources :hours
  resources :users
  resources :roles

  root to: 'profile#index'
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_role, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    #@role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    #@role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
=begin    def set_role
      @role = Role.find(params[:id])
    end
=end
    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>